name: Upload Python Package to PYPI

on:
  pull_request:
    branches: main
    types: closed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: python -m pip install poetry
      - name: Update patch version of package
        id: versionUpdate
        run: |
          poetry version patch
          echo "::set-output version=$(poetry version -s)"
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git fetch origin main
          git rebase origin/main
          git add .
          git commit -m "${{ steps.versionUpdate.outputs.version }} release"
          git push origin main
      - name: Build and upload python package
        env:
          username: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry publish --build -u ${username} -p ${password}
